[package]
name = "multi_model"
version = "0.1.0"
edition = "2024"

[dependencies]

image = "0.25.9"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
rayon = "1.10.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde_json = "1.0"

